# Homework Starter — Stage 03: Python Fundamentals

## Instructions
Fill in the cells below to complete your homework. Refer to lecture examples.

In [1]:
# --- packages this notebook needs (uncomment and run once, then re-comment) ---
# !pip install numpy
# !pip install pandas
# !pip install matplotlib

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1. NumPy Operations

In [ ]:
# TODO: Create a NumPy array and perform vectorized operations

In [5]:
import numpy as np

prices = np.array([100, 101, 102, 103, 104, 107, 111])

price_plus_1pct = prices * 1.01
price_change = prices - prices[0]

print("Original prices:", prices)
print("Prices after +1%:", price_plus_1pct)
print("Change from first price:", price_change)

Original prices: [100 101 102 103 104 107 111]
Prices after +1%: [101.   102.01 103.02 104.03 105.04 108.07 112.11]
Change from first price: [ 0  1  2  3  4  7 11]

## 2. Compare Loop vs Vectorization

In [ ]:
# TODO: Compare speed using %timeit

In [6]:
import numpy as np

arr = np.arange(1, 1000001)

def loop_double(x):
    result = []
    for value in x:
        result.append(value * 2)
    return result

def vectorized_double(x):
    return x * 2

print("Loop:")
%timeit loop_double(arr)

print("Vectorized:")
%timeit vectorized_double(arr)

Loop:
152 ms ± 7.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
Vectorized:
1.3 ms ± 79.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

## 3. Load and Inspect Dataset

In [10]:
from pathlib import Path

HW3 = Path(
    r"E:\Bootcamp Repo\Bootcamp_Yunqiang_Lyu\homework\homework03"
)

for d in [
    "data/raw",
    "data/processed",
    "src"
]:
    (HW3 / d).mkdir(parents=True, exist_ok=True)

print("Created:", HW3)

Created: E:\Bootcamp Repo\Bootcamp_Yunqiang_Lyu\homework\homework03

In [ ]:
# TODO: Load CSV and inspect with .head(), .info(), .describe()

In [2]:
from pathlib import Path
import pandas as pd

data_path = Path("data/raw/starter_data.csv")

df = pd.read_csv(data_path)

print("First 5 rows:")
display(df.head())

print("\nDataset info:")
df.info()

print("\nSummary statistics:")
display(df.describe())

First 5 rows:

  category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  10 non-null     object
 1   value     10 non-null     int64
 2   date      10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

Summary statistics:

           value
count  10.000000
mean   17.600000
std     7.381659
min    10.000000
25%    12.250000
50%    14.500000
75%    23.250000
max    30.000000

## 4. Summary Statistics and Groupby

In [ ]:
# TODO: Perform groupby and save output to data/processed/

In [3]:
from pathlib import Path

# Summary statistics for numeric columns
summary = df.describe()

print("Summary Statistics:")
display(summary)

# Check available columns
print("\nColumns in dataset:")
print(df.columns.tolist())

# Groupby aggregation by category
if "category" in df.columns:
    grouped = df.groupby("category").mean(numeric_only=True)

    print("\nGroupby Results:")
    display(grouped)
else:
    print("\nNo 'category' column found. Please check the actual column name above.")

# Create processed folder
processed_dir = Path("data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

# Save summary statistics
summary_path = processed_dir / "summary.csv"
summary.to_csv(summary_path)

print("\nSaved summary to:")
print(summary_path.resolve())

Summary Statistics:

           value
count  10.000000
mean   17.600000
std     7.381659
min    10.000000
25%    12.250000
50%    14.500000
75%    23.250000
max    30.000000

Columns in dataset:
['category', 'value', 'date']

Groupby Results:

              value
category
A         11.500000
B         15.666667
C         27.666667

Saved summary to:
E:\Bootcamp Repo\Bootcamp_Yunqiang_Lyu\homework\homework03\data\processed\summary.csv